# Generated by Django 4.1.5 on 2023-02-02 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='COA',
            fields=[
                ('코드', models.IntegerField(primary_key=True, serialize=False)),
                ('계정명', models.CharField(max_length=30, null=True)),
                ('계정_대분류', models.CharField(max_length=20, null=True)),
                ('계정_중분류', models.CharField(max_length=20, null=True)),
                ('계정_소분류', models.CharField(max_length=20, null=True)),
                ('재무제표', models.CharField(max_length=20, null=True)),
                ('비고', models.TextField(null=True)),
            ],
            options={
                'verbose_name_plural': 'COA',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('제품코드', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('제품명', models.CharField(max_length=30)),
                ('포장단위', models.CharField(max_length=30)),
                ('제약사', models.CharField(max_length=30)),
                ('보험코드', models.CharField(max_length=20)),
                ('표준코드', models.CharField(max_length=20)),
                ('기준가', models.IntegerField()),
                ('급여', models.IntegerField()),
                ('구분', models.CharField(max_length=20)),
                ('성문코드', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Product',
            },
        ),
    ]
