# Generated by Django 4.1.5 on 2023-02-24 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_coa_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('부서이름', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Incumbent',
            fields=[
                ('사번', models.IntegerField(primary_key=True, serialize=False)),
                ('구분', models.CharField(max_length=4)),
                ('이름', models.CharField(max_length=10)),
                ('영문이름', models.CharField(max_length=20)),
                ('근무지', models.CharField(max_length=5)),
                ('팀', models.CharField(max_length=5)),
                ('직급', models.CharField(max_length=5)),
                ('직책', models.CharField(max_length=5, null=True)),
                ('입사일', models.DateField(null=True)),
                ('근속일', models.IntegerField()),
                ('주민등록번호', models.CharField(max_length=20, null=True)),
                ('생년월일', models.DateField(null=True)),
                ('연락처', models.CharField(max_length=20, null=True)),
                ('비상연락망', models.CharField(max_length=20, null=True)),
                ('회사_이메일', models.EmailField(max_length=254, null=True)),
                ('개인_이메일', models.EmailField(max_length=254, null=True)),
                ('주소', models.TextField(null=True)),
                ('최종학력', models.CharField(max_length=10, null=True)),
                ('학위', models.CharField(max_length=10, null=True)),
                ('학교', models.CharField(max_length=10, null=True)),
                ('전공', models.CharField(max_length=10, null=True)),
                ('학점', models.CharField(max_length=10, null=True)),
                ('입사구분', models.CharField(max_length=10, null=True)),
                ('경력사항1', models.CharField(max_length=10, null=True)),
                ('경력사항2', models.CharField(max_length=10, null=True)),
                ('경력사항3', models.CharField(max_length=10, null=True)),
                ('경력사항4', models.CharField(max_length=10, null=True)),
                ('경력사항5', models.CharField(max_length=10, null=True)),
                ('자격사항1', models.CharField(max_length=10, null=True)),
                ('자격사항2', models.CharField(max_length=10, null=True)),
                ('자격사항3', models.CharField(max_length=10, null=True)),
                ('자격사항4', models.CharField(max_length=10, null=True)),
                ('자격사항5', models.CharField(max_length=10, null=True)),
                ('어학사항1', models.CharField(max_length=10, null=True)),
                ('어학사항2', models.CharField(max_length=10, null=True)),
                ('어학사항3', models.CharField(max_length=10, null=True)),
                ('어학사항4', models.CharField(max_length=10, null=True)),
                ('어학사항5', models.CharField(max_length=10, null=True)),
                ('부서', models.ForeignKey(db_column='부서', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='부서', to='erp.department')),
            ],
        ),
    ]
