# Generated by Django 4.1.5 on 2023-02-27 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0004_alter_incumbent_개인_이메일_alter_incumbent_경력사항1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Retiree',
            fields=[
                ('사번', models.IntegerField(primary_key=True, serialize=False)),
                ('구분', models.CharField(max_length=4)),
                ('이름', models.CharField(max_length=10)),
                ('영문이름', models.CharField(max_length=20)),
                ('근무지', models.CharField(max_length=5)),
                ('부서', models.CharField(blank=True, max_length=10, null=True)),
                ('팀', models.CharField(max_length=5)),
                ('직급', models.CharField(max_length=5)),
                ('직책', models.CharField(blank=True, max_length=5, null=True)),
                ('입사일', models.DateField(blank=True, null=True)),
                ('근속일', models.IntegerField(blank=True)),
                ('주민등록번호', models.CharField(blank=True, max_length=20, null=True)),
                ('생년월일', models.DateField(blank=True, null=True)),
                ('연락처', models.CharField(blank=True, max_length=20, null=True)),
                ('비상연락망', models.CharField(blank=True, max_length=20, null=True)),
                ('회사_이메일', models.EmailField(blank=True, max_length=254, null=True)),
                ('개인_이메일', models.EmailField(blank=True, max_length=254, null=True)),
                ('주소', models.TextField(blank=True, null=True)),
                ('최종학력', models.CharField(blank=True, max_length=10, null=True)),
                ('학위', models.CharField(blank=True, max_length=10, null=True)),
                ('학교', models.CharField(blank=True, max_length=10, null=True)),
                ('전공', models.CharField(blank=True, max_length=10, null=True)),
                ('학점', models.CharField(blank=True, max_length=20, null=True)),
                ('입사구분', models.CharField(blank=True, max_length=10, null=True)),
                ('경력사항1', models.CharField(blank=True, max_length=10, null=True)),
                ('경력사항2', models.CharField(blank=True, max_length=10, null=True)),
                ('경력사항3', models.CharField(blank=True, max_length=10, null=True)),
                ('경력사항4', models.CharField(blank=True, max_length=10, null=True)),
                ('경력사항5', models.CharField(blank=True, max_length=10, null=True)),
                ('자격사항1', models.CharField(blank=True, max_length=10, null=True)),
                ('자격사항2', models.CharField(blank=True, max_length=10, null=True)),
                ('자격사항3', models.CharField(blank=True, max_length=10, null=True)),
                ('자격사항4', models.CharField(blank=True, max_length=10, null=True)),
                ('자격사항5', models.CharField(blank=True, max_length=10, null=True)),
                ('어학사항1', models.CharField(blank=True, max_length=10, null=True)),
                ('어학사항2', models.CharField(blank=True, max_length=10, null=True)),
                ('어학사항3', models.CharField(blank=True, max_length=10, null=True)),
                ('어학사항4', models.CharField(blank=True, max_length=10, null=True)),
                ('어학사항5', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='incumbent',
            name='학점',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
