# Generated by Django 4.1.5 on 2023-02-27 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0005_retiree_alter_incumbent_학점'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncumbentUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upfile', models.FileField(blank=True, null=True, upload_to='uploads')),
            ],
        ),
    ]
