# Generated by Django 4.1.5 on 2023-02-28 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0006_incumbentupdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incumbent',
            name='영문이름',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='retiree',
            name='영문이름',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
