# Generated by Django 4.1.5 on 2023-02-28 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0007_alter_incumbent_영문이름_alter_retiree_영문이름'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incumbent',
            name='학교',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='retiree',
            name='학교',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
