# Generated by Django 4.1.5 on 2023-02-28 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0008_alter_incumbent_학교_alter_retiree_학교'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incumbent',
            name='직급',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='incumbent',
            name='직책',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='retiree',
            name='직급',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='retiree',
            name='직책',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
