# Generated by Django 4.1.5 on 2023-02-28 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0009_alter_incumbent_직급_alter_incumbent_직책_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incumbent',
            name='팀',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='retiree',
            name='팀',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
