# Generated by Django 4.1.5 on 2023-02-28 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0011_alter_incumbent_근속일_alter_retiree_근속일'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Retiree',
        ),
        migrations.AddField(
            model_name='incumbent',
            name='퇴직여부',
            field=models.BooleanField(default=1),
        ),
    ]
