# Generated by Django 4.1.5 on 2023-02-28 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0014_alter_incumbent_퇴직여부'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incumbent',
            name='퇴직여부',
            field=models.BooleanField(default=False),
        ),
    ]
